### ISSUE TITLE
Use tsconfig bases for the tsconfig in the template

### ISSUE THREAD

**Issue by orta** [formik/tsdx#753] opened 2020-07-07 15:49 UTC
### Current Behavior

Today my TSConfig looks like:

```json
{
  "include": ["src", "types", "test"],
  "compilerOptions": {
    "target": "es5",
    "module": "esnext",
    "lib": ["dom", "esnext"],
    "importHelpers": true,
    "declaration": true,
    "sourceMap": true,
    "rootDir": "./",
    "strict": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "noImplicitThis": true,
    "alwaysStrict": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "moduleResolution": "node",
    "baseUrl": "./",
    "paths": {
      "*": ["src/*", "node_modules/*"]
    },
    "jsx": "react",
    "esModuleInterop": true
  }
}
```

It could be:

```json
{
  "include": ["src", "types", "test"],
  "extends": "@tsconfig/tsdx"
}
```

Then when I make a change specific to my  project it's _very_ obvious:

```json
{
  "include": ["src", "types", "test"],
  "extends": "@tsconfig/tsdx",
  "compilerOptions": {
        "noImplicitReturns": false
  }
}
```

See:
- https://github.com/microsoft/TypeScript-Website/issues/130#issuecomment-652399262 
- https://github.com/tsconfig/bases

### Who does this impact? Who is this for?

Should be useful to anyone regardless of their TS level

### Describe alternatives you've considered

Don't, which is also OK

**Comment by agilgur5** [comment] 2020-07-07 22:11
Sounds like a duplicate of #634. That hasn't gotten many comments, however, though lots of related issues in support of it and this sounds directly in support for a `tsconfig` preset.

@orta is there any reason to use https://github.com/tsconfig/bases / `@tsconfig/tsdx` as opposed to hosting it under `@tsdx/tsconfig`?

**Closed by agilgur5** 2020-07-07 22:11 UTC

**Comment by orta** [comment] 2020-07-08 01:52
No strong reason other than network effects of it being the same tool others use
