### ISSUE TITLE
Is it possible to run the script using tsdx?

### ISSUE THREAD

**Issue by woss** [formik/tsdx#749] opened 2020-06-21 14:26 UTC
Apart from the single entry point i would like to have a demo of the library as well. Is is possible to use tsdx like ts-node?

**Comment by PGA68** [comment] 2020-06-30 14:45
\Projects>npx tsdx create try_02_tsdx
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @babel/plugin-proposal-nullish-coalescing-operator@^7.10.4.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of '@babel/preset-env'
npm ERR! notarget

npm ERR! A complete log of this run can be found in:
npm ERR!     ....\Roaming\npm-cache\_logs\2020-06-30T14_31_06_175Z-debug.log
Install for [ 'tsdx@latest' ] failed with code 1

**Comment by agilgur5** [comment] 2020-07-07 22:31
The issue template was removed here and the description is quite short, so it's difficult to tell what the intent here is.

Is your library a `bin` script? A demo wouldn't need to use `ts-node` as the library is already transpiled. Unless you're saying a demo of the app inside of a TypeScript application. In either case, it sounds like you'd want an [`example/` directory similar to the React template](https://github.com/formik/tsdx/tree/17ffcd215f78a4e9d6936644cbeab332f6439088/templates/react/example) but modified for a script or a Node app instead.

This is outside the scope of TSDX the library but could be an idea for another template TSDX could have.

>  Is is possible to use tsdx like ts-node?

TSDX does not run your code per #478, it just builds the library (and can also test, lint, etc it). If you're looking to run a Node app instead of a Node library, then this would be a duplicate of #654 . It's unclear what the intent of that statement was, so I'm not sure how else to answer.

**Closed by agilgur5** 2020-07-07 22:31 UTC
Labels: removed issue template

**Comment by woss** [comment] 2020-07-08 06:43
@agilgur5 i think you answered perfectly. ✋ yes, the intent is to have something similar to the `example` folder, because so many time you want to test the lib before you actually build it. 
Thanks for your time
